Collecting git+https://github.com/rom1504/DALLE-pytorch.git
  Cloning https://github.com/rom1504/DALLE-pytorch.git to /private/var/folders/p1/9kcbj3ks6rb68kf529fcz5x40000gn/T/pip-req-build-sdw4cu8z
  Running command git clone --filter=blob:none --quiet https://github.com/rom1504/DALLE-pytorch.git /private/var/folders/p1/9kcbj3ks6rb68kf529fcz5x40000gn/T/pip-req-build-sdw4cu8z
  Resolved https://github.com/rom1504/DALLE-pytorch.git to commit c4330e35d96708328bbe54a4ae8f6355056755a7
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting axial_positional_embedding (from dalle-pytorch==0.11.3)
  Using cached axial_positional_embedding-0.3.12-py3-none-any.whl.metadata (4.3 kB)
Collecting DALL-E (from dalle-pytorch==0.11.3)
  Using cached DALL_E-0.1-py3-none-any.whl.metadata (433 bytes)
Collecting einops>=0.3 (from dalle-pytorch==0.11.3)
  Using cached einops-0.8.1-py3-none-any.whl.metadata (13 kB)
Collecting ftfy (from dalle-pytorch==0.11.3)
  Using cached ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pillow in ./.conda/lib/python3.11/site-packages (from dalle-pytorch==0.11.3) (11.3.0)
Collecting regex (from dalle-pytorch==0.11.3)
  Using cached regex-2024.11.6-cp311-cp311-macosx_11_0_arm64.whl.metadata (40 kB)
Requirement already satisfied: taming-transformers in ./taming-transformers (from dalle-pytorch==0.11.3) (0.0.1)
Collecting tokenizers (from dalle-pytorch==0.11.3)
  Using cached tokenizers-0.21.2-cp39-abi3-macosx_11_0_arm64.whl.metadata (6.8 kB)
Requirement already satisfied: torch>=1.6 in ./.conda/lib/python3.11/site-packages (from dalle-pytorch==0.11.3) (2.7.1)
Collecting torchvision (from dalle-pytorch==0.11.3)
  Using cached torchvision-0.22.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.1 kB)
Collecting transformers (from dalle-pytorch==0.11.3)
  Using cached transformers-4.53.1-py3-none-any.whl.metadata (40 kB)
Requirement already satisfied: tqdm in ./.conda/lib/python3.11/site-packages (from dalle-pytorch==0.11.3) (4.67.1)
Collecting youtokentome (from dalle-pytorch==0.11.3)
  Using cached youtokentome-1.0.6.tar.gz (86 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  [1;31merror[0m: [1msubprocess-exited-with-error[0m
  
  [31mÃ—[0m [32mpython setup.py egg_info[0m did not run successfully.
  [31mâ”‚[0m exit code: [1;36m1[0m
  [31mâ•°â”€>[0m [31m[6 lines of output][0m
  [31m   [0m Traceback (most recent call last):
  [31m   [0m   File "<string>", line 2, in <module>
  [31m   [0m   File "<pip-setuptools-caller>", line 35, in <module>
  [31m   [0m   File "/private/var/folders/p1/9kcbj3ks6rb68kf529fcz5x40000gn/T/pip-install-010uti2p/youtokentome_f5a322376dd2422e9a04fbeede8281c5/setup.py", line 5, in <module>
  [31m   [0m     from Cython.Build import cythonize
  [31m   [0m ModuleNotFoundError: No module named 'Cython'
  [31m   [0m [31m[end of output][0m
  
  [1;35mnote[0m: This error originates from a subprocess, and is likely not a problem with pip.
[1;31merror[0m: [1mmetadata-generation-failed[0m

[31mÃ—[0m Encountered error while generating package metadata.
[31mâ•°â”€>[0m See above for output.

[1;35mnote[0m: This is an issue with the package mentioned above, not pip.
[1;36mhint[0m: See above for details.
